---
title: "Chloroquine concentration-dependent QRS widening"
author: "James Watson"
date: "6/12/2020"
output:
  html_document:
    df_print: paged
    keep_md: yes
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = TRUE, cache.comments = FALSE, 
                      include = TRUE, echo = TRUE, 
                      fig.width = 9, fig.height = 9,
                      fig.pos = 'H', 
                      dev = 'png', dpi = 300)
library(knitr)
library(gtools)
library(rstan)
library(RColorBrewer)
RUN_MODELS=F
```

Show R version and package versions
```{r}
sessionInfo()
```

Important parameters for the analysis/visualisation
```{r}
#****** Parameters for the analysis *******
plasma_to_whole_blood_ratio = 4 # conversion from plasma to whole blood for the healthy volunteer concentration data
Weight_interested = 70 # displays results for chosen weight - has to be multiple of 5 and between 40 and 90!
```

## Data from self-poisoning cohorts and healthy volunteers

Data from Riou were extracted from published graph (see Figure 3 in NEJM Riou et al, 1988) using WebPlotDigitiser

```{r pooled_data}
pooled_data = read.csv('Pooled_QRS_data.csv')

# do the conversion from plasma to whole blood for the healthy volunteers
# study = 1 is self-poisoning (Clemessy)
# study = 2 is self-poisoning (Megarbane)
# study = 3 is healthy volunteers
pooled_data$CQ_uMol[pooled_data$study==3] =
  pooled_data$CQ_uMol[pooled_data$study==3]*plasma_to_whole_blood_ratio
```

```{r Sfig_raw_QRS_data, fig.width=10, fig.height=9}
# some nice colors for the plots
col_study = RColorBrewer::brewer.pal(n = 3, name = 'Set1')

ind_clem = pooled_data$study==1
# jitter the self-poisoning QRS data
ys = rep(0, nrow(pooled_data)); ys[ind_clem] = rnorm(sum(ind_clem),mean = 0,sd = 1)

par(las=1, bty='n', family='serif',cex.lab=1.5, cex.axis=1.5)
plot(log10(pooled_data$CQ_uMol), ys+pooled_data$QRS, xaxt='n',
     col = col_study[pooled_data$study], ylab='QRS duration (msec)', 
     xlab=expression(paste('Whole blood chloroquine concentration (',mu,'mol/L)')), 
     pch = pooled_data$died+1,main='Raw QRS data (no bias or outlier adjustement)')
axis(1, at = seq(-1, 2, by = 0.5), labels = round(10^seq(-1, 2, by = 0.5),1))
legend('topleft',  pch = c(1,1,1,1,2),
       legend = c('Healthy volunteers (620 mg base)',
                  'Self-poisoning (Clemessy)',
                  'Self-poisoning (Megarbane)',
                  'Survivors','Fatal cases'),
       col = c(col_study[c(3,1,2)],'black','black'), inset = 0.03)
abline(h=150, v=1, lty=2)
```


## Stan model

Emax type model

```{r}
Conc_QRS_Emax = "
functions {
  real sigmoid(real log10_conc, real ed50, real log_slope, real max_effect, real min_effect){
    return max_effect + (min_effect-max_effect)/(1 + exp(exp(log_slope)*(log10_conc-ed50)));
  }
}

data {
  int<lower=0> N1; // number of paired concentration-QRS datapoints
  int<lower=0> N2; // number of QRS datapoints in absence of drug for healthy volunteers
  int<lower=0> N_HV; // the number of healthy volunteers 
  int<lower=0,upper=N_HV> ID1[N1]; // for the interindividual variability - zero is dummy value
  int<lower=0,upper=N_HV> ID2[N2]; // for the interindividual variability - zero is dummy value
  real log10_conc[N1];
  real QRS_drug[N1];
  real QRS_nodrug[N2];
  int<lower=1,upper=3> study[N1]; // 1 is Clemessy self-poisoning; 2 is Megarbane self-poisoning; 3 is healthy volunteers
  
  // prior parameters
  real ed50_mu;
  real ed50_sd;
  real max_effect_prior_mu;
  real max_effect_prior_sd;
  real min_effect_prior_mu;
  real min_effect_prior_sd;
  real log_slope_prior_mu;
  real log_slope_prior_sd;
  real bias_term_prior_mu;
  real bias_term_prior_sd;
  real mu_normal_mean;
  real mu_normal_sd;
  real sigma_i_prior;
}

parameters {
  real log_slope;
  real min_effect;  
  real max_effect;
  real bias_term;
  real ed50;
  real mu_i[N_HV];
  real mu_normal; // the value min_effect - mu_normal is mean normal QRS value
  real<lower=0> sigma1;
  real<lower=0> sigma2;
  real<lower=0> sigma3;
  real<lower=0> sigma_i; // for inter-individual variability in healthy volunteers
}

model {
  // Prior
  bias_term ~ normal(bias_term_prior_mu,bias_term_prior_sd);
  log_slope ~ normal(log_slope_prior_mu, log_slope_prior_sd);
  ed50 ~ normal(ed50_mu, ed50_sd);
  max_effect ~ normal(max_effect_prior_mu,max_effect_prior_sd);
  min_effect ~ normal(min_effect_prior_mu,min_effect_prior_sd);
  mu_i ~ normal(0,sigma_i);
  mu_normal ~ normal(mu_normal_mean,mu_normal_sd);
  
  sigma_i ~ exponential(sigma_i_prior); 
  sigma1 ~ normal(25,5);
  sigma2 ~ normal(15,5);
  sigma3 ~ normal(2,1);
  
  // Likelihood
  for (j in 1:N1){
    real QRS_pred;
    QRS_pred = sigmoid(log10_conc[j], ed50, log_slope, max_effect, min_effect);
    if(study[j] == 1){
      QRS_drug[j] ~ normal(QRS_pred + bias_term, sigma1);
    } 
    if(study[j] == 2){
      QRS_drug[j] ~ normal(QRS_pred, sigma2);
    }
    if(study[j] == 3) {
      QRS_drug[j] ~ normal(QRS_pred + mu_i[ID1[j]], sigma3);
    }
  }
  for (j in 1:N2){
    QRS_nodrug[j] ~ normal(min_effect - mu_normal + mu_i[ID2[j]], sigma3);
  }
}
"
if(RUN_MODELS) conc_QRS_mod = stan_model(model_code = Conc_QRS_Emax)
```

## Fit main model to prospective data

```{r runstan}
N_iter = 10^5
N_thin = 100
N_chains = 8
#options(mc.cores = N_chains) - broken in current R version!
prior_params = list(max_effect_prior_mu = 180,
                    max_effect_prior_sd = 10, 
                    min_effect_prior_mu = 90,
                    min_effect_prior_sd = 4,
                    log_slope_prior_mu = 1,
                    log_slope_prior_sd = 1,
                    ed50_mu = 1.3, 
                    ed50_sd = 1,
                    bias_term_prior_mu = -20,
                    bias_term_prior_sd = 5,
                    mu_normal_mean = 3,
                    mu_normal_sd = 1,
                    sigma_i_prior = 0.2)

# QRS values above 200 are not physiologically possible so we truncate at 200
pooled_data$QRS[pooled_data$QRS > 200] = 200
# only use the non-zero concentration-QRS datapoints
ind_notinf = pooled_data$CQ_uMol > 0 

CQ_data = list(N1 = as.integer(sum(ind_notinf)),
               N2 = as.integer(sum(!ind_notinf)),
               log10_conc = log10(pooled_data$CQ_uMol[ind_notinf]),
               QRS_drug = pooled_data$QRS[ind_notinf],
               QRS_nodrug = pooled_data$QRS[!ind_notinf],
               study = as.integer(pooled_data$study[ind_notinf]),
               ID1 = as.integer(pooled_data$ID[ind_notinf]),
               ID2 = as.integer(pooled_data$ID[!ind_notinf]),
               N_HV = as.integer(max(pooled_data$ID)))

if(RUN_MODELS){
  mod_QRS_full = sampling(conc_QRS_mod,
                          data=c(CQ_data, prior_params),
                          iter = N_iter, thin = N_thin, chains = N_chains)
  save(mod_QRS_full, file = 'mod_QRS_full.stanout')
} else {
  load('mod_QRS_full.stanout')
}
```


```{r}
sigmoid = function(log10_conc, ed50, log_slope, max_effect, min_effect){
  return (max_effect + (min_effect-max_effect)/(1 + exp(exp(log_slope)*(log10_conc-ed50))))
}
thetas = extract(mod_QRS_full)

xs1 = seq(0,2,length.out = 100)
ys1 = array(dim = c(100,length(thetas$log_slope)))

xs2 = seq(-1,1,length.out = 100)
ys2 = array(dim = c(100,length(thetas$log_slope)))

xs3 = seq(-1,2,length.out = 100)
ys3 = array(dim = c(100,length(thetas$log_slope)))
for(i in 1:length(thetas$log_slope)){
  ys1[,i] = sigmoid(log10_conc = xs1, ed50 = (thetas$ed50[i]),
                   log_slope = (thetas$log_slope[i]),
                   max_effect = (thetas$max_effect[i]), 
                   min_effect = (thetas$min_effect[i])) + 
    rnorm(1,0,thetas$sigma2[i])
  
  ys2[,i] = sigmoid(log10_conc = xs2, ed50 = (thetas$ed50[i]),
                   log_slope = (thetas$log_slope[i]),
                   max_effect = (thetas$max_effect[i]), 
                   min_effect = (thetas$min_effect[i])) + 
    rnorm(1,0,thetas$sigma3[i]) + rnorm(1,0,thetas$sigma_i)
  
  ys3[,i] = sigmoid(log10_conc = xs3, ed50 = (thetas$ed50[i]),
                   log_slope = (thetas$log_slope[i]),
                   max_effect = (thetas$max_effect[i]), 
                   min_effect = (thetas$min_effect[i])) 
}
```


```{r QRS_fit, fig.width=10, fig.height=9}
par(las=1, bty='n', family='serif',cex.lab=1.5, cex.axis=1.5)

# random jitter for visualisation
jitter_QRS = rnorm(nrow(pooled_data), mean = , sd = 1*as.numeric(pooled_data$study==1))
plot(x = log10(pooled_data$CQ_uMol), panel.first = grid(),
     y = pooled_data$QRS - mean(thetas$bias_term)*as.numeric(pooled_data$study==1) + jitter_QRS, 
     xaxt='n', col = col_study[pooled_data$study],ylab='QRS duration (msec)', 
     xlab=expression(paste('Whole blood chloroquine concentration (',mu,'mol/L)')), 
     pch = pooled_data$died+1, xlim = c(-1,2))
axis(1, at = seq(-1, 2, by = 0.5), labels = round(10^seq(-1, 2, by = 0.5),1))
legend('topleft',  pch = c(1,1,1,2),
       legend = c('Healthy volunteers (620 mg base)',
                  'Self-poisoning (Clemessy)',
                  'Self-poisoning (Megarbane)',
                  'Survivors','Fatal cases'),
       col = c(col_study[c(3,1,2)],'black','black'), inset = 0.03)

QRS_normal = array(dim = max(pooled_data$ID))
for(i in 1:max(pooled_data$ID)){
  # Take the mean of duplicated normal QRS values in the healthy volunteers
  QRS_normal[i] = mean(pooled_data$QRS[pooled_data$CQ_uMol==0 & pooled_data$ID==i])
}
# then we look at quantiles of these 16 datapoints
qs=quantile(QRS_normal, probs = c(0,1,0.5))

qrs_normal_estimated = mean(thetas$min_effect) + colMeans(thetas$mu_i) - mean(thetas$mu_normal)
qs_estimated = quantile(qrs_normal_estimated, probs = c(0,1,0.5))
polygon(x = c(-3,3,3,-3),y = c(qs_estimated[1],qs_estimated[1],qs_estimated[2],qs_estimated[2]), 
        col = adjustcolor('grey',alpha.f = .4),border = NA)

abline(h=150, v=1, lty=2)
lines(xs3,rowMeans(ys3),lwd=3)

lines(xs1,apply(ys1,1,quantile,probs=0.025),lwd=2,lty=2, col=col_study[2])
lines(xs1,apply(ys1,1,quantile,probs=0.975),lwd=2,lty=2, col=col_study[2])

lines(xs2,apply(ys2,1,quantile,probs=0.025),lwd=2,lty=2, col=col_study[3])
lines(xs2,apply(ys2,1,quantile,probs=0.975),lwd=2,lty=2, col=col_study[3])


abline(h=qs_estimated[3], lty=1, col='grey',lwd=3)

points(log10(pooled_data$CQ_uMol), 
       pooled_data$QRS - mean(thetas$bias_term)*as.numeric(pooled_data$study==1)+jitter_QRS, 
       col = col_study[pooled_data$study],  pch = pooled_data$died+1)

# The prolongation from normal to E_min
quantile(thetas$mu_normal, probs = c(0.025,.5,0.975))
```

Increase in QRS at 3 umol/L
```{r QRS_increase_3umolL}
vals = array(dim = length(thetas$log_slope))
for(i in 1:length(thetas$log_slope)){
  vals[i] = sigmoid(log10_conc = log10(3), ed50 = thetas$ed50[i], log_slope = thetas$log_slope[i],
          min_effect = thetas$min_effect[i], max_effect = thetas$max_effect[i]) -
    (thetas$min_effect[i] - thetas$mu_normal[i])
}
hist(vals, xlab='Estimated mean QRS widening at 3 umol/L (msec)',main='', yaxt='n',
     breaks = 50, ylab='',border = NA)

writeLines(sprintf('At 3umol/L the median increase in QRS is %s (95%% CI is %s - %s)',
                   round(median(vals),1), round(quantile(vals,0.025),1), round(quantile(vals,0.975),1)))
```


```{r priors_vs_posteriors_QRS}
par(mfrow=c(3,4),las=1, cex.lab=1)
hist(thetas$max_effect, freq = F,breaks = 50,main = '', border = NA,
     xlab = 'Emax QRS (msec)', col = 'grey',ylab='', yaxt='n')
xs = seq(min(thetas$max_effect), max(thetas$max_effect), length.out=500)
lines(xs, dnorm(xs, mean = prior_params$max_effect_prior_mu, 
                sd = prior_params$max_effect_prior_sd), lwd=3, col='red')

hist(thetas$min_effect, freq = F,breaks = 50, main = '', border = NA,
     xlab = 'Emin QRS (msec)', col = 'grey',ylab='', yaxt='n')
xs = seq(min(thetas$min_effect), max(thetas$min_effect), length.out=500)
lines(xs, dnorm(xs, mean = prior_params$min_effect_prior_mu, 
                sd = prior_params$min_effect_prior_sd), lwd=3, col='red')

hist(thetas$bias_term,freq=F,breaks = 50,main = '', xlab = 'Bias term (Clemessy, msec)', 
     col = 'grey',ylab='', yaxt='n',border = NA)
xs = seq(min(thetas$bias_term), max(thetas$bias_term), length.out=500)
lines(xs, dnorm(xs, mean = prior_params$bias_term_prior_mu, sd = prior_params$bias_term_prior_sd), lwd=3, col='red')

hist(thetas$ed50, freq=F,breaks = 50,main = '', xlab = 'ED_50 (log_10 concentration)', col = 'grey',
     ylab='', yaxt='n',border = NA)
xs=seq(0,2,length.out = 2000); 
lines(xs, dnorm(xs,mean = prior_params$ed50_mu,sd = prior_params$ed50_sd),col='red',lwd=3)

hist(thetas$log_slope, freq=F,breaks = 50,main = '', xlab = 'Slope coefficient (on log scale)', 
     col = 'grey',ylab='', yaxt='n',border = NA)
xs=seq(0,2,length.out = 2000); 
lines(xs, dnorm(xs,mean = prior_params$log_slope_prior_mu,sd = prior_params$log_slope_prior_sd),
      col='red',lwd=3)


hist(thetas$mu_normal, freq=F,breaks = 50,main = '', border = NA,
     xlab = 'Decrease for steady state QRS (msec)', col = 'grey', ylab='', yaxt='n')
xs=seq(0,10,length.out = 500); 
lines(xs, dnorm(xs,mean = prior_params$mu_normal_mean,sd = prior_params$mu_normal_sd),col='red',lwd=3)

hist(thetas$sigma1, freq=F,breaks = 50,main = '', xlab = 'Sigma Clemessy', 
     col = 'grey',ylab='', yaxt='n',border = NA)
xs=seq(0,50,length.out = 500); 
lines(xs, dnorm(xs,mean = 25, sd = 5),col='red',lwd=3)

hist(thetas$sigma2, freq=F,breaks = 50,main = '', xlab = 'Sigma Megarbane', 
     col = 'grey',  ylab='', yaxt='n',border = NA)
lines(xs, dnorm(xs,mean = 2, sd = 1),col='red',lwd=3)

hist(thetas$sigma3, freq=F,breaks = 50,main = '', xlab = 'Sigma healthy volunteers', 
     col = 'grey',  ylab='', yaxt='n',border = NA)
lines(xs, dnorm(xs,mean = 2, sd = 1),col='red',lwd=3)


hist(thetas$sigma_i, freq=F,breaks = 50,main = '', border = NA,
     xlab = 'Inter-individual sigma (healthy volunteers)', col = 'grey',
     ylab='', yaxt='n')
lines(xs, dexp(xs,rate = prior_params$sigma_i_prior),col='red',lwd=3)
```


```{r}
pooled_data = dplyr::filter(pooled_data, study %in% c(1,2))
table( (pooled_data$QRS-mean(thetas$bias_term)*as.numeric(pooled_data$study==1)) > 150, pooled_data$CQ_uMol>10)

mod=glm(died ~ log(CQ_uMol) + QRS + study, family = binomial, data = pooled_data)
summary(mod)

writeLines(sprintf('The odds ratio is %s', round(exp(10*0.022706),1)))
```

